apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: kms
    {{- include "kms-app.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.data | nindent 2 }}