apiVersion: v1
kind: Secret
metadata:
  name: kms-secret
  labels:
    app: kms
type: Opaque
data:
  # Default values (base64 encoded)
  # database-url: cG9zdGdyZXM6Ly9rbXM6a21zX3Bhc3N3ZUBrbnMtZGI6NTQzMi9rbXM/c3NsbW9kZT1kaXNhYmxl
  # admin-username: YWRtaW4=
  # admin-password: YWRtaW4=
  # auth-secret: cGxlYXNlLWNoYW5nZS1tZS1pbi1wcm9kdWN0aW9u
  database-url: cG9zdGdyZXM6Ly9rbXM6a21zX3Bhc3N3ZUBrbnMtZGI6NTQzMi9rbXM/c3NsbW9kZT1kaXNhYmxl
  admin-username: YWRtaW4=
  admin-password: YWRtaW4=
  auth-secret: cGxlYXNlLWNoYW5nZS1tZS1pbi1wcm9kdWN0aW9u